mysql:
  adapter: mysql
  database: queuez_test
  username: root
  encoding: utf8

mysql2:
  adapter: mysql2
  database: queuez_test
  username: root
  encoding: utf8

postgresql:
  adapter: postgresql
  database: queuez_test
  username: postgres

sqlite3:
  adapter: sqlite3
  database: ":memory:"
